services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post123
    ports:
      - 4321:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=code001
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  pgdata: 
  mongodata: