services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post123
    ports:
      - 4321:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 